### ISSUE TITLE
Support for directed networks

### ISSUE THREAD

**Issue by PCK1992** [benjamin-w-campbell/fergm#3]
Hi,

I tried running the `fergm` command on a directed network and got the following message:

`Error in prepare_fergm_data(net, form) : Directed networks not yet supported.`

Is there any way to run it on directed networks?

**Comment by benjamin-w-campbell** [comment]
Unfortunately, as the error implies we have not yet added functionality allowing for directed networks.  There is no timeline for when this functionality will be added which is certainly a shame as this is clearly an important issue. However, I have stepped away from academia and have few incentives to add such functionality at this time.  

If you have Stan skills and an interest in adding these functions, let me know.  Otherwise, I will be sure to bring this up should someone express an interest in taking over the Maintainer role.  

Closing this down.

**Comment by benjamin-w-campbell** [comment]
Also, feel free to reach out to me at bencam92@gmail.com if you'd like to have an extended conversation about this.
